site_name: React Mini Projects
nav:
  - Start Here: index.md
  - Multiplication Tables: 1-multiplication-tables.md
  - Color Picker: 2-color-picker.md
  - Move Pixel: 3-move-div.md
  - Speech Synthesis: 4-speech-synthesis.md
  - Right Click Menu: 5-right-click-menu.md
  - React Konva: 6-konva-react.md
  - React Router DOM + Bulma: 7-react-router-dom-bulma.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
