site_name: My Docs
nav:
  - Start Here: index.md
  - Multiplication Tables: 1-multiplication-tables.md
  - Color Picker: 2-color-picker.md
  - Move Pixel: 3-move-div.md
  - Speech Synthesis: 4-speech-synthesis.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
